version: "3.2"

services:
  wundergraph:
    container_name: wundergraph
    image: wundergraph
    restart: always
    build:
      context: .
    environment:
      - "WG_PUBLIC_NODE_URL=https://${DOMAIN}"
    ports:
      - "172.17.0.1:28271:9991"
