version: "3.2"

services:
  wundergraph:
    # image: elestio4test/wundergraph:latest
    container_name: wundergraph
    image: wundergraph
    restart: always
    build:
      context: .
    environment:
      - "WG_PUBLIC_NODE_URL=https://${DOMAIN}"
    ports:
      - "172.17.0.1:28271:9991"
    # volumes:
    #   - ./.wundergraph/wundergraph.config.ts:/app/.wundergraph/wundergraph.config.ts
    #   - ./.wundergraph/wundergraph.operations.ts:/app/.wundergraph/wundergraph.operations.ts
    #   - ./.wundergraph/wundergraph.server.ts:/app/.wundergraph/wundergraph.server.ts
